### ISSUE TITLE
[서버] 개발 환경 구축

### ISSUE THREAD

**Issue by hongmj37** [BBack-BBoo-Team/Sebadog-book-server#1]
완료 후 Repository에 PUSH

**Comment by hongmj37** [comment]
초기 개발환경 구축 완료

**Comment by hongmj37** [comment]
@Si-Hyeak-KANG @HYUNSUK331

**Comment by Si-Hyeak-KANG** [comment]
👍🏼 넘무너무 굿

**Comment by Si-Hyeak-KANG** [comment]
클론해서 실행했을 때 문제도 없고, 굿굿입니다
3가지 피드백 조심스레 올려봐융 

### 1) Root 폴더
- 현재 Repositroy를 보면 첫 페이지에 app 폴더가 root로 지정되었습니다
 
![image](https://github.com/BBack-BBoo-Team/Sebadog-book-server/assets/79829085/32ed5363-0f32-4739-9c49-2641226a9815)

이렇게 했을 때의 문제점은 아래 이미지처럼 클론했을 때, intellij가 프로젝트 정보를 읽지 못합니다. 보다시피 jdk도 다시 설정하고, 실행도 안되쥬
다행히도 똑똑한 intellij가 app 경로 안에 gradle을 읽을까요? 라고 물어봐줘서 사실 크~은 문제는 아닙니당
하지만 gitignore, 추후 배포 스크립트 등 설정 시 오류가 빈번하게 발생할 수 있어서 번거로울 수 있습니다.
<img width="1461" alt="스크린샷 2024-01-11 오전 9 48 26" src="https://github.com/BBack-BBoo-Team/Sebadog-book-server/assets/79829085/234a08a0-da23-4027-a1de-93a5fe63131f">

- 개선방법
<img width="1015" alt="스크린샷 2024-01-11 오전 9 40 44" src="https://github.com/BBack-BBoo-Team/Sebadog-book-server/assets/79829085/15b1762d-e590-499f-ad2f-eaf01e590684">

위 이미지 예시처럼 해당 뎁스가 루트 폴더로 만들면 되겠습니다.

**Comment by Si-Hyeak-KANG** [comment]
## 2) Gitignore 적용

github에 프로젝트를 올릴 때, 불필요한 파일들이 있습니다. 예를 들어서 intellij 설정 정보가 담긴 .idea 파일, 빌드(실행)할 때마다 변경되는 build 파일, out 파일, 중요한 정보가 들어간 파일 등등

### 현재 문제

불필요한 파일들도 github에 올라가면서, 아래 이미지처럼 실행만 해도 변경되는 파일이 많아집니다. 불필요할 뿐더러 충돌까지 유발합니다.
<img width="387" alt="image" src="https://github.com/BBack-BBoo-Team/Sebadog-book-server/assets/79829085/fc154c3a-65e6-4215-b486-bc9acd30012b">

### 개선방법
<img width="880" alt="image" src="https://github.com/BBack-BBoo-Team/Sebadog-book-server/assets/79829085/31ef69c5-76e7-4706-8bdf-2a127fab38aa">

위 이미지와 같이 최상단 경로에 생성된 .gitignore 파일에 변경 감지에서 제외할 경로를 입력합니다.

> 그런데 도무지 무슨 파일들을 제외시켜야 할지 모르겠다 하면 아래 링크 고고

### 사이트 사용 방법

https://www.toptal.com/developers/gitignore/

<img width="1305" alt="image" src="https://github.com/BBack-BBoo-Team/Sebadog-book-server/assets/79829085/a262e6fa-16fa-4c9a-b059-ea30458214cf">

- 아래 이미지처럼 검색바 입력 후 생성 버튼 클릭

그러면 아래처럼 스크립트 출력 -> 이거 복사해서 .gitignore에 붙여넣기 -> 그 다음 변경 감지 테스트

<img width="1161" alt="스크린샷 2024-01-11 오전 10 08 44" src="https://github.com/BBack-BBoo-Team/Sebadog-book-server/assets/79829085/7e6c173c-7af3-4f7a-abbf-d2bb0fe586c3">

**Comment by Si-Hyeak-KANG** [comment]
## 3) 마지막으로 
- yml에 jpa 설정 후 직접 db연결해서 실행되는지 체크 필요!
- main 실행을 때와 test 실행했을 때 각각 어떤 db가 실행되는지 체크 필요!

**Comment by Si-Hyeak-KANG** [comment]
@Si-Hyeak-KANG @hongmj37 @HYUNSUK331 
서버 환경 설정 완료~
