### ISSUE TITLE
[서버] 도서 등록 기능 개발

### ISSUE THREAD

**Issue by hongmj37** [BBack-BBoo-Team/Sebadog-book-server#7]
- [x] local db 생성 (my sql)
- [x] 테이블 명세서 → JPA 객체 만들기 (자동으로 실행하면 생성됨)
- [x] 패키지 구조 : Controller, Service, ServiceImpl, Repository, Vo(Model)
- [x] 요구사항 기능 구현
- [x] API 명세서
- [x] 테스트

**Comment by hongmj37** [comment]
서버 등록 기능 개발 start !

**Comment by hongmj37** [comment]
정정 ! 내일부터 start !

**Comment by Si-Hyeak-KANG** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ어이없넼ㅋㅋ

**Comment by Si-Hyeak-KANG** [comment]
질문!!
1) VO와 Entity, Dto의 차이가 무엇인가요?
2) ServiceImpl, Service 처럼 인터페이스를 활용한 이유가 무엇인가요?

**Comment by hongmj37** [comment]
왜 알면서 물어바 -3-

**Comment by hongmj37** [comment]
1. Entity는 실제로 데이터베이스의 테이블과 매핑되는 객체

VO는 그냥 순수한 객체 머 아님 순수 그잡채

DTO는 데이터 이동을 도와주는 객체 (머 컨트롤에서 서비스단으로 갈때 등)

**Comment by hongmj37** [comment]
2. 독립성, 유지보수를 위하여

추가적인 설명은 @Si-Hyeak-KANG 가 하도록 .

**Comment by Si-Hyeak-KANG** [comment]
ㅋㅋㅋㅋㅋㅋ그래도 다 답변해줬네 감사합니다
